### PR TITLE
Adding methods to python client.

### PR DESCRIPTION
**Pull request by ytjohn**
Added several functions to the python client.
- ensure asset  - if an asset doesn't exist, create it
- get/create/delete/update/ensure assettype
- ping - ping the collins api
- soft update - update an existing asset key, changing only if required
- optimized imports, corrected some comment spacing

### CODE REVIEW

**Comment by ytjohn** [comment]
Don't have CLA filled out, will work on that today.

**Comment by Primer42** [comment]
This is awesome @ytjohn!  Do you want to add yourself to the author list? https://github.com/tumblr/collins/blob/master/support/python/collins_client/setup.py#L8

**Comment by ytjohn** [comment]
Will do (re: author's list)

**Comment by byxorna** [comment]
This LGTM (i cant approve? @Primer42 harsh...)

**Comment by discordianfish** [comment]
@Primer42 Ping? Can this get merged? Looks straight forward to me.

**Pull request merged**
