### PR TITLE
Make blake's password 'admin:first' in the example users.conf files

### PR DESCRIPTION
**Pull request by Primer42**
This makes testing file authentication much easier, since it keeps
blake's password the same in all auth methods

@tumblr/collins

### CODE REVIEW

**Comment by roymarantz** [comment]
:+1:

**Comment by byxorna** [comment]
I dont follow... isnt the password already 'admin:first'? I know a simple `docker run -p 9000:9000 tumblr/collins` lets me log in with `blake` `admin:first`.

**Comment by Primer42** [comment]
@byxorna - `default` auth is not file auth - it's a weird in-memory database setup. 

https://github.com/tumblr/collins/blob/master/conf/authentication.conf#L3
http://tumblr.github.io/collins/configuration.html#authentication
https://github.com/tumblr/collins/blob/master/app/collins/util/security/MixedAuthenticationProvider.scala#L18

Take a look at [this issue comment](https://github.com/tumblr/collins/issues/422#issuecomment-206418780) for a full explanation, but the hash in the example `users.conf` files does not actually match the hash of `admin:first`

**Comment by Primer42** [comment]
Actually, I just looked at the mock authentication provider - it doesn't seem like any of the examples in users.conf match.  I'm going to make all of them match, so I don't think we know what these passwords are anymore.

**Comment by Primer42** [comment]
Thinking about it, I'm not sure if this is the right approach.  We may be better off having different passwords, and documenting what they are, so that people can turn on file auth and immediately know if it's working or if its still hitting the mock auth provider.  I think both options have benefits and downsides, and I'm not sure which is best....

**Comment by byxorna** [comment]
@Primer42 what i think is more likely is that the algorithm that your X year newer htpasswd is using is different than what was used when generating these files originally.

**Comment by Primer42** [comment]
@byxorna see [the comment I linked to](https://github.com/tumblr/collins/issues/422#issuecomment-206418780) - it's not doing anything complicate (base64 of a sha1), I tested with the raw scala code.  And I turned on file auth with this file, and I could not log in as blake.  This is definitely a different password.

**Comment by Primer42** [comment]
**bump**

**Comment by byxorna** [comment]
I like having some well documented users/pws on the getting started wiki (and make clear the roles they are in as well). I.e. `root`, `opsuser`, `joeuser`, etc.

**Comment by Primer42** [comment]
Hahaha
http://tumblr.github.io/collins/index.html#quickstart
The passwords are documented, in Authentication in that section.
So I think what we need to do is just make the docs better, and put this in a more logical place.

**Pull request closed without merging**
