### PR TITLE
switched tests to use a console logger with a root of INFO.  This should...

### PR DESCRIPTION
**Pull request by nsauro**
... reduce logback spammage in tests

### CODE REVIEW

**Comment by nsauro** [comment]
Just trying to fix logback in the test scope.  I switched to use a console logger, and this should reduce all of that awful log spam we get when running tests.

**Comment by nsauro** [comment]
https://travis-ci.org/tumblr/collins/jobs/52287071

That is the output now

**Comment by byxorna** [comment]
lgtm

**Comment by maddalab** [comment]
lgtm

**Pull request merged**
