### PR TITLE
Add id to log endpoints

### PR DESCRIPTION
**Pull request by Primer42**
Two changes
- When creating a log, it now returns the log entry, not just a boolean
- You can retrieve logs by id
I also added these abilities to `collins-client`

This will make the logging api much more useful, allowing programs to store and retrieve specific log messages, instead of asking an asset all of its logs, and hoping you can use regexes to find the one you need.

@nsauro @maddalab @byxorna @roymarantz @defect

### CODE REVIEW

**Comment by maddalab** [comment]
no new tests?

**Comment by Primer42** [comment]
@maddalab good call - tests added :smile:

**Comment by defect** [comment]
Ruby changes LGTM. Don't forget to update the gh-pages docs. :)

**Comment by Primer42** [comment]
Yeah, I'm going to do a big doc update once this is out.

**Comment by byxorna** [comment]
LGTM bu i havent tested

**Pull request merged**
