### PR TITLE
Updated minAddress to respect startAt

### PR DESCRIPTION
**Pull request by davidblum**
This bug fix resolves the issue where startAt is not respected (or added after) if IP addresses have already been assigned to pools or IPMI.  This is in references the issue linked below.

https://github.com/tumblr/collins/issues/428#issuecomment-199524123

### CODE REVIEW

**Comment by maddalab** [comment]
Awesome fix. Lgtm

**Comment by davidblum** [comment]
```
[error] error while loading <root>, Error accessing /home/travis/.ivy2/cache/org.apache.hadoop/hadoop-hdfs/jars/hadoop-hdfs-2.6.0.jar
```

Please re-test when you have a moment.  Thanks!

**Comment by byxorna** [comment]
LGTM

**Comment by Primer42** [comment]
Nice catch! LGTM
@davidblum I know this is a real pain, but I need to ask you to sign this document before we can merge this....
https://github.com/tumblr/collins/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla
Can you post back here or email me once that's done?

**Comment by davidblum** [comment]
@Primer42 Signed and sent to legal.

**Comment by Primer42** [comment]
Thanks @davidblum!

**Pull request merged**
