### PR TITLE
added input search field in top bar

### PR DESCRIPTION
**Pull request by MaximeDevalland**

### CODE REVIEW

**Comment by maddalab** [comment]
Thanks @MaximeDevalland 

I'll pull it down and test it. Gennaro was trying something like this and Laquan wanted it, so definitely worth merging

@byxorna @Primer42 @defect @roymarantz

**Comment by maddalab** [comment]
@MaximeDevalland I tried this and am probably doing something incorrect. I did not see the browser make a request when

**Comment by byxorna** [comment]
screen shot 2015-06-28 at 9 27 07 am

Looks like the margins are a bit screwy.

**Comment by byxorna** [comment]
Also, its not readily apparent to the user that clicking the "Collins" link on the left takes you to the search page. Nor is it clear which field the search input up top is actually searching on (tag? hostname?).

The search also isnt functional; it isnt sending any parameters when posting, so the resources page returned is totally unfiltered and just returns all assets

**Comment by MaximeDevalland** [comment]
Thanks for you feedback @maddalab @byxorna 

I've fixed the css and placeholder but I don't why, the search is working for me.

**Comment by MaximeDevalland** [comment]
@maddalab Is there anything I can do to help expedite the merge?
Thanks

**Comment by maddalab** [comment]
Sorry. I'll definitely take a look tonight.

**Comment by maddalab** [comment]
@MaximeDevalland thank you for the change. I'll go ahead and merge. I'm going to build on this and make a couple of small changes.

**Pull request merged**
