### PR TITLE
Fix issue with invoking authentication twice

### PR DESCRIPTION
**Pull request by maddalab**
Summary:
Invoking authentication twice, once during form validation,
and once during action execution, causes login to fail
in systems using OTP (One time password) authentication
schemes.

@byxorna @defect @Primer42 @roymarantz @mattikus

https://github.com/tumblr/collins/issues/315

### CODE REVIEW

**Comment by Primer42** [comment]
In general, this LGTM.  How was it tested?

**Comment by byxorna** [comment]
LGTM. worth testing?

**Comment by mattikus** [comment]
Not sure how useful it is, but it's been tested in my environment and works
as expected.

**Comment by maddalab** [comment]
thanks matt.  Matt tested in an OTP setup with LDAP.

I tested with file and db auth.

**Pull request merged**
