### PR TITLE
format provisioning errors less shittily

### PR DESCRIPTION
**Pull request by byxorna**
Provisioning errors are hard to read right now. Change that to format preformatted code with like... `<pre><code>...</code></pre>`. @Primer42 @defect @schallert @roymarantz @maddalab

### CODE REVIEW

**Comment by Primer42** [comment]
LGTM

**Comment by roymarantz** [comment]
:+1:  for the code, but does the "caller" have any trouble with this?  it is likely to change the "shape" of the  displayed message.  e.g if the message used to be displayed as a single line and the formating shapes it into multi-line...

**Comment by byxorna** [comment]
@roymarantz this is web view only. "clients" are humans clicking buttons. This does not impact responses given over API at all

**Comment by roymarantz** [comment]
that is what I was hoping for.  thaks

**Comment by byxorna** [comment]
@Primer42 merge?

**Pull request merged**
