### PR TITLE
[WIP] fix tests

### PR DESCRIPTION
**Pull request by maddalab**

### CODE REVIEW

**Comment by maddalab** [comment]
@byxorna @defect @Primer42 

Now that is a successful build finally

**Comment by byxorna** [comment]
Wow, this is excellent! This LGTM. Thanks for doing this! :star2: :volcano: :boom: :tada: :cake: :sushi:

**Comment by Primer42** [comment]
So awesome LGTM

**Comment by sparciii** [comment]
:+1: :cookie:

**Comment by maddalab** [comment]
@sparciii hey now.

Ok with that last commit, a change to `build.sbt` we have the best of all worlds as it now stands. merging.

**Pull request merged**
