### PR TITLE
Fixing documentation examples

### PR DESCRIPTION
**Pull request by defect**
I've recently come across a couple of places where the example JSON responses in the docs aren't correct. Either the JSON is broken, or they don't match what's actually returned from collins. This fixes the errors I've found.

@Primer42 @byxorna @roymarantz

### CODE REVIEW

**Comment by roymarantz** [comment]
:+1:  the changes look safe (mostly spacing)

**Comment by defect** [comment]
Some spacing yeah, but that doesn't break the JSON. The problems were mostly with how various parts of the JSON blobs were nested.

**Comment by byxorna** [comment]
LGTM! :cake:

**Comment by Primer42** [comment]
LGTM

**Pull request merged**
