### PR TITLE
IPMI generation API docs

### PR DESCRIPTION
**Pull request by byxorna**
#512 #513

### CODE REVIEW

**Comment by byxorna** [comment]
@roymarantz @qx-xp @defect @komapa RFR please!

**Comment by roymarantz** [comment]
👍

**Comment by roymarantz** [comment]
fyi you can use @tumblr/collins to poke reviews

**Comment by byxorna** [comment]
@roymarantz i think some settings need to be tweaked on that team; outside people cannot use that mention handle:
screen shot 2017-03-14 at 12 57 57 pm

**Pull request merged**
