### PR TITLE
change all instances of 2015 to 2016

### PR DESCRIPTION
**Pull request by sushruta**
:%s/2015/2016/g

@defect @Primer42 @roymarantz @schallert

will squash before merging.

### CODE REVIEW

**Comment by roymarantz** [comment]
:+1:

**Comment by byxorna** [comment]
LGTM. Please squash before merge?

**Comment by Primer42** [comment]
Definitely squash please.  Otherwise, LGTM

**Comment by sushruta** [comment]
the tests seem to be failing for a reason unrelated to my PR. Is this expected?

**Pull request merged**
