### PR TITLE
[docs] ipmi: update password length requirements

### PR DESCRIPTION
**Pull request by schallert**
Updates the docs to reflect the changes in https://github.com/tumblr/collins/pull/327

RFR @tumblr/systems

### CODE REVIEW

**Comment by roymarantz** [comment]
so is it > 4 and  < 28 or >= 4 and <= 28?

**Comment by schallert** [comment]
@roymarantz it's >= 4 and <= 28, however throughout our documentation we use "between" to signify that (for example: [api.yml](https://github.com/tumblr/collins/blob/f83ae0074d7d24a39f57bbddb3221f985db422d4/_data/api.yml#L1850-L1858)). As we seem to have established that convention, I believe we can follow it without further specification.

**Comment by roymarantz** [comment]
as long as we are consistently ambiguous :-)  :+1:

**Comment by byxorna** [comment]
LGTM

**Comment by Primer42** [comment]
LGTM

**Pull request merged**
