### PR TITLE
fix timeout deprecation warning in collins client request

### PR DESCRIPTION
**Pull request by byxorna**
```/Users/gabe/code/collins/support/ruby/collins-client/lib/collins/api/util/requests.rb:82:in `http_call': Object#timeout is deprecated, use Timeout.timeout instead.```

This fixes that.

### CODE REVIEW

**Comment by byxorna** [comment]
@Primer42 @maddalab @Primer42 @schallert @roymarantz

**Comment by Primer42** [comment]
LGTM - should this also be a minor version bump?

**Comment by byxorna** [comment]
Up to you @Primer42. I was going to leave it to those who can actually release the gem to make the decision (and commit) to bump the release when appropriate, as I cannot anymore :(

**Comment by Primer42** [comment]
@byxorna yeah if you do a version bump in this PR, once it's merged I'll make sure the new gem gets deployed to public rubygems.

**Comment by byxorna** [comment]
@Primer42 done.

**Comment by roymarantz** [comment]
:+1:  for the code and version bump too.

**Pull request merged**
