### PR TITLE
Allow skipping chassis tag verification

### PR DESCRIPTION
**Pull request by discordianfish**
With the feature intakeChassisTagOptional enabled, collins will skip the
chassis tag verification in the intake process if the chassis tag isn't
set. It will allow adding the asset tag in the final intake step.

This is based on top of #492

### CODE REVIEW

**Comment by byxorna** [comment]
Eyeballing it lgtm, but i havent tested all the different configuration modes.

**Comment by discordianfish** [comment]
@byxorna Best would be to add some tests.. but since there are none for the intake process so far and I'm not very experienced with scala I'd need some help with that.

**Comment by byxorna** [comment]
@discordianfish the testing framework is kind of complicated, so I dont have much guidance here. @Primer42 ?

**Comment by Primer42** [comment]
Yeah, similar review to @byxorna - code looks good, but I haven't tested it thoroughly. 
There aren't any tests around intake, and I think it's out of scope to ask you to write a big part of the test framework as part of this PR.

**Comment by discordianfish** [comment]
Ok, then let's test this manually. I've tried it locally and deployed it to our systems. So far works as expected but our setup is tiny and the intake process not yet much used.

**Comment by discordianfish** [comment]
Looks like this project is dead outside tumblr at least, so closing this.

**Pull request closed without merging**
