### PR TITLE
Trying to revive the tests

### LINKED ISSUE #483: Fix failing tests
Looks like the tests are failing due to incompatible dependencies:
- https://travis-ci.org/tumblr/collins/jobs/171454189#L192

Can look into this next week.

### PR DESCRIPTION
**Pull request by discordianfish**
Closes #483

### CODE REVIEW

**Comment by byxorna** [comment]
👍

**Comment by discordianfish** [comment]
I think this is a good start. This is still failing though:

 RUN_RUBY=true RUN_SCALA=false GEM_NAME=collins-state

Could use some help fixing this. Did it ever worked? If so, I can try git-bisect'ing to found what broke it.

**Comment by discordianfish** [comment]
@Primer42 can we get this merged? Or even better, somehow figure out how to get those things merged quicker in the future?

**Comment by Primer42** [comment]
LGTM

**Comment by discordianfish** [comment]
@Primer42 Then go merge it! :) Is there even another maintainer active?

**Pull request merged**
