### PR TITLE
Fix the color scheme

### PR DESCRIPTION
**Pull request by Primer42**
@byxorna @roymarantz @defect

### CODE REVIEW

**Comment by roymarantz** [comment]
What's wrong with the colors?  Shouldn't you include a before and after picture :-)
:+1:

**Comment by Primer42** [comment]
Before:

After:

**Comment by Primer42** [comment]
Real Before:

Real after:

**Comment by maddalab** [comment]
ohh man basic bootstrap theme is soooooo ..... basic

**Comment by Primer42** [comment]
I think you meant to say 'wonderful' instead of 'basic'

**Comment by byxorna** [comment]
:cake: :cake: :cake:

**Pull request merged**
